---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orbitalsync
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      orbitalsync:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mattwebbio/orbital-sync
              tag: 1.8.4
            env:
              PRIMARY_HOST_BASE_URL: http://192.168.1.250/
              SECONDARY_HOST_1_BASE_URL: http://pihole-web
            envFrom: &envFrom
              - secretRef:
                  name: pihole-secret
