apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.4.3
  enableSuperuserAccess: true
  startDelay: 30
  stopDelay: 100
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart ##@@ Cannot use switchover with 1 instance
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    enableAlterSystem: true
  storage:
    size: 8Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immichdb-secret
      dataChecksums: true
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        # - CREATE EXTENSION IF NOT EXISTS "vector";
        # - ALTER ROLE "immich" WITH "superuser";
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg-immich/
      endpointURL: http://minio.storage.svc.cluster.local:9000
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster postgres16-v6
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: minio-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: minio-secret-access-key
