---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k10
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k10-secret
    template:
      engineVersion: v2
      data:
        auth: "{{ .htpasswd }}"
  dataFrom:
    - extract:
        key: k10
