# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: crowdsec-secret
    template:
      type: Opaque
      data:
        ENROLL_KEY: "{{ .ENROLL_KEY }}"
        BOUNCER_KEY_INGRESS: "{{ .BOUNCER_KEY_INGRESS }}"
  dataFrom:
    - extract:
        key: crowdsec
