---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-new
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-new-secret
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbhost immichpostgres17-rw.database.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .IMMICH_POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: *dbPass
        IMMICH_SERVER_URL: http://immich-server-new.media.svc.cluster.local:3001
        IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning-new.media.svc.cluster.local:3003
        PUBLIC_IMMICH_SERVER_URL: https://images.maunder.co
        REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
        REDIS_PORT: "6379"
        REDIS_DBINDEX: "1"
        TZ: "Europe/London"
  dataFrom:
    - extract:
        key: immich-new
    - extract:
        key: cloudnative-pg
