---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server-new
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      immich:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: immich-new-secret

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.142.1
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
            env:
              UPLOAD_LOCATION: /usr/src/app/upload
            envFrom:
              - secretRef:
                  name: immich-new-secret
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 3001
        fsGroup: 3001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: immich
        ports:
          http:
            port: 2283
    ingress:
      app:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        hosts:
          - host: &host images.maunder.co
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      photos:
        existingClaim: immich-nfs
        globalMounts:
          - path: /usr/src/app/upload
      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Pictures
        globalMounts:
          - path: /storage/Pictures

