---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app geyser-connect
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      geyser-connect:
        replicas: 1
        strategy: Recreate
        containers:
          geyser-connect:
            image:
              repository: ghcr.io/jokajak/geyser-mc
              tag: 2.3.0-2
            probes:
              liveness:
                enabled: false
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "nc -z -u localhost 19132"
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness:
                enabled: false
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "nc -z -u localhost 19132"
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
            resources:
              requests:
                cpu: 1000m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      geyser-connect:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external-dns.alpha.kubernetes.io/hostname: minecraft.maunder.co
          io.cilium/lb-ipam-ips: 192.168.1.197
        ports:
          minecraft:
            port: 19132
            protocol: UDP
    serviceAccount:
      create: true
      name: *app
    persistence:
      config:
        enabled: true
        existingClaim: geyser-connect
        advancedMounts:
          geyser-connect:
            geyser-connect:
              - path: /var/lib/geyser
