# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  timeout: 10m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      minecraft:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: 'true'
        pod:
          annotations:
            reloader.stakater.com/auto: 'true'
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java21@sha256:3b97ca8f48507f1c85e8d7a32aee5c9bd7e09d4e96584b71aac0b878c8f1d16c
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  exec: &mc-health {command: ["mc-health"]}
              readiness: *probes
              startup:
                <<: *probes
                spec:
                  initialDelaySeconds: 60
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *mc-health
            env:
              # Server Configuration
              ## General
              EULA: 'true'
              SERVER_NAME: 'MPOF'
              TYPE: FABRIC
              FORCE_REDOWNLOAD: 'true'

              # renovate: depName=minecraft datasource=custom.minecraft versioning=semver-coerced
              VERSION: 1.21.1
              MOTD: 'Play Nice!'
              DIFFICULTY: easy
              SPAWN_PROTECTION: 0
              SEED: '-2135836821937050197'
              FORCE_REDOWLOAD: 'true'
              ENABLE_WHITELIST: 'true'
              # Logging
              ENABLE_ROLLING_LOGS: 'true'
              LOG_TIMESTAMP: 'true'
              # Performance
              JVM_XX_OPTS: '-XX:MaxRAMPercentage=75'
              MAX_MEMORY: 8G
              USE_AIKAR_FLAGS: 'true'
              SNOOPER_ENABLED: 'false'
              VIEW_DISTANCE: 14
              ## Mods
              REMOVE_OLD_MODS: 'true'
              MODRINTH_DEFAULT_VERSION_TYPE: release
              MODRINTH_PROJECTS: >
                spark,
                bluemap,
                geyser:beta,
                floodgate:beta
              # https://vanillatweaks.net/share#oNYxlz
              VANILLA_TWEAKS_SHARE_CODES: oNYxlz # Coord HUD, Anti-Endermen Griefing
              ## RCON
              RCON_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: minecraft-secret
                    key: rcon_password
              ENABLE_QUERY: 'true'
              # Whitelist / Ops
              WHITELIST:
                valueFrom:
                  secretKeyRef:
                    name: minecraft-secret
                    key: whitelist
              EXISTING_WHITELIST_FILE: SYNC_FILE_MERGE_LIST
              OPS:
                valueFrom:
                  secretKeyRef:
                    name: minecraft-secret
                    key: ops
              EXISTING_OPS_FILE: SYNCHRONIZE
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 250m
                memory: 4Gi
              limits:
                memory: 8Gi
    service:
      minecraft:
        controller: minecraft
        type: LoadBalancer    # https://kubernetes.io/blog/2022/05/23/service-ip-dynamic-and-static-allocation/
        clusterIP: 192.168.1.196 # FIXME: Remove if/when playit supports hostname tunnel endpoints
        ports:
          java:
            port: 25565
            protocol: TCP
          bedrock:
            port: 19132
            protocol: UDP
          map:
            port: 8100
          metrics:
            port: 25585
    serviceMonitor:
      metrics:
        enabled: true
        serviceName: minecraft
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m
    ingress:
      map:
        className: internal
        hosts:
          - host: &host minecraft.maunder.co
            paths:
              - path: /
                service:
                  identifier: minecraft
                  port: map
        tls:
          - hosts:
              - *host
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
    persistence:
      data:
          type: persistentVolumeClaim
          size: 10Gi
          accessMode: ReadWriteOnce
      bluemap:
        type: persistentVolumeClaim
        size: 20Gi
        accessMode: ReadWriteOnce
      bluemap-config:
        type: configMap
        name: minecraft-bluemap
        globalMounts:
          - path: /data/config/bluemap/core.conf
            subPath: core.conf
            readOnly: true
          - path: /data/config/bluemap/storages/file.conf
            subPath: file.conf
            readOnly: true
          # Maps configuration
          - path: /data/config/bluemap/maps/nether.conf
            subPath: nether.conf
            readOnly: true
          - path: /data/config/bluemap/maps/end.conf
            subPath: end.conf
            readOnly: true
      geyser:
        type: configMap
        name: geyser-config
        globalMounts:
          - path: /data/config/Geyser-Fabric/config.yml
            subPath: config.yml
            readOnly: true
