---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geyser-connect
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
