# kubernetes/apps/external-secrets/onepassword-connect/app/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      onepassword-connect:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          api:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.7.2@sha256:6aa94cf713f99c0fa58c12ffdd1b160404b4c13a7f501a73a791aa84b608c5a1
            env:
              - name: XDG_DATA_HOME
                value: /config
              - name: OP_HTTP_PORT
                value: "80"
              - name: OP_BUS_PORT
                value: "11220"
              - name: OP_BUS_PEERS
                value: "localhost:11221"
              - name: OP_SESSION
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 15
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.7.2@sha256:fe527ed9d81f193d8dfbba4140d61f9e8c8dceb0966b3009259087504e5ff79c
            env:
              - name: XDG_DATA_HOME
                value: /config
              - name: OP_HTTP_PORT
                value: "8081"
              - name: OP_BUS_PORT
                value: "11221"
              - name: OP_BUS_PEERS
                value: "localhost:11220"
              - name: OP_SESSION
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8081
                  initialDelaySeconds: 15
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: onepassword-connect
        ports:
          http:
            port: 80
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config