# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
    template:
      type: Opaque
      data:
        ENCRYPTION_PASSWORD: "{{ .VAULTWARDEN_BACKUP_PASS }}"
        PUSH_INSTALLATION_ID: "{{ .PUSH_INSTALLATION_ID }}"
        PUSH_INSTALLATION_KEY: "{{ .PUSH_INSTALLATION_KEY }}"
  dataFrom:
    - extract:
        key: vaultwarden
