---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.30.5-alpine
            env:
              DATA_FOLDER: "data"
              ICON_CACHE_FOLDER: "data/icon_cache"
              ATTACHMENTS_FOLDER: "data/attachments"
              DOMAIN: "https://bw.${SECRET_DOMAIN}"
              TZ: "Europe/London"
              SIGNUPS_ALLOWED: "false"
              INVITATIONS_ALLOWED: "true"
              ORG_EVENTS_ENABLED: "true"
              PASSWORD_ITERATIONS: "321000"
              EVENTS_DAYS_RETAIN: "730"
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_ADDRESS: 0.0.0.0
              REQUIRE_DEVICE_EMAIL: "true"
              SHOW_PASSWORD_HINT: "false"
              SMTP_HOST: smtp-relay.network.svc.cluster.local
              SMTP_FROM: vaultwarden@${SECRET_DOMAIN}
              SMTP_FROM_NAME: vaultwarden@${SECRET_DOMAIN}
              SMTP_PORT: 25
              SMTP_SECURITY: "off"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: vaultwarden-db
        globalMounts:
          - path: /data
      backups:
        type: nfs
        server: "192.168.1.100"
        path: "/mnt/Data/Backup/vaultwarden"
        globalMounts:
          - path: /backups
    defaultPodOptions:
      annotations:
        secret.reloader.stakater.com/reload: *app
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.maunder.co
        className: "external"
        hosts:
          - host: "bw.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
