---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.34.1-alpine
            env:
              DATA_FOLDER: "data"
              ICON_CACHE_FOLDER: "data/icon_cache"
              ATTACHMENTS_FOLDER: "data/attachments"
              DOMAIN: "https://bw.${SECRET_DOMAIN}"
              TZ: "Europe/London"
              SIGNUPS_ALLOWED: "false"
              INVITATIONS_ALLOWED: "false"
              ORG_EVENTS_ENABLED: "true"
              PASSWORD_ITERATIONS: "321000"
              EVENTS_DAYS_RETAIN: "730"
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_ADDRESS: 0.0.0.0
              REQUIRE_DEVICE_EMAIL: "true"
              SHOW_PASSWORD_HINT: "false"
              PUSH_ENABLED: "true"
              SMTP_HOST: smtp-relay.network.svc.cluster.local
              SMTP_FROM: "vaultwarden@maunder.co"
              SMTP_FROM_NAME: "vaultwarden@maunder.co"
              SMTP_PORT: 25
              SMTP_SECURITY: "off"
              PUSH_RELAY_URI: "https://api.bitwarden.eu"
              PUSH_IDENTITY_URI: "https://identity.bitwarden.eu"
            envFrom: &envFrom
              - secretRef:
                  name: vaultwarden-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
          backups:
            # Restore with:
            #   gpg --decrypt backup.tar.xz.gpg > backup.tar.xz
            #   tar -xJvf ./backup/data.tar.xz -C /data/
            image:
              repository: bruceforce/vaultwarden-backup
              tag: 2.1.0
            env:
              TIMESTAMP: true
              DELETE_AFTER: 30
              CRON_TIME: "0 * * * *"
              BACKUP_DIR: '/backups'
              BACKUP_ON_STARTUP: true
              GID: 0
              UID: 0
            envFrom: *envFrom
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: vaultwarden-db
        globalMounts:
          - path: /data
      backups:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Backup/vault
        globalMounts:
          - path: /backups
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
      annotations:
        secret.reloader.stakater.com/reload: *app
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/custom-http-errors: 403,404,500,501,502,503
          external-dns.alpha.kubernetes.io/target: external.maunder.co
        className: "external"
        hosts:
          - host: "bw.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
