apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pjAJPVzNMbsU0aV2MHMB2cg5a2XHCIyLY+u+A/TgxXoDn5+D,iv:IUsl491PqvqrrWA44dC1s/n15JlvUZ0gEx1Z/hi7QMk=,tag:C3EAVKMimnzard3YqIxV7w==,type:str]
    credentials.json: ENC[AES256_GCM,data:wG6vO/5HPhxfTZJewlY7MxvePd2IsKFVRaWWlWym+x5qS6RUSinrZOr/nfQ03DcEcAxNeD8AdmqObdkmWCE6talyTYVst+7bUTrAIUWBR9ozO+4k4TB7hQt10iJriSb7XmBCbeGWieTh8P4saNCDZnyjdPDbOuqr9dgslZ4gBvhyTw4nILgIzLq+S7bs6HTt9CzIyj4K1Nlrh4pUbO+BB4FW+r5oKzjUyTqzk6PvIQ==,iv:9g+s2OV7oxm5SD0BEpmlCQJ3fSzYg6TohS5THAv99/Y=,tag:qqZmLIDCLtRlF5oyi7TMNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZG5rN2tOQWdmY0FDR0hs
            aUpkcHZqR1Btc2NkZWtNK3BHREJQMHE2Mmc0CkgyNlEwVENpa2xiOVltamZ6VGo4
            MU9vRVNQWmhkS1BvNldjSmhXamg3azAKLS0tIG9vTEJxZzRnZWIvcERRUWtscmtP
            WkFnRDhkWUtlMUdzQUNSaXVlUkRSUnMKW3PMJRUmCHjmo9jsmqq1dtbsP/o1b6KS
            8XvZtOMuGZL2u8VGBzo92GE3qPLrN2mYeLvDx4HiaBaLzRumaCsSRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T20:31:41Z"
    mac: ENC[AES256_GCM,data:txgj6kpBsC1LJkvdfod+EcQ0wdgWZqIHHrkDjnMJxK89yPVt2aNWQkEMyIqCTRd0cR/v1aTV8ddIM3xIYJGKyWDNxIxytqo62t9mrwnwtyD1glmJW+yXkL54IBMvkunETj8yeENQAhQwXgQZk9j8nv8Z/j8Ype8aFb/ap6F6kso=,iv:EdIod0kryvyoyJlE198iStPsQbWNADYBHvMS5qI+Noo=,tag:PRwUlCHKX5Gb9LtrSJuUWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
