apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:t9DWzpmTiuLLYI466IOC8FPGMLX8JHoxBqfyTQl8pEjlvhDQ,iv:k8aXqgd17ZezYoAiM+ouMZl1DXZsGyF2uVZGpBT/PgY=,tag:NU1x4+ZJYqd3oors7lGPOA==,type:str]
    credentials.json: ENC[AES256_GCM,data:CGpeGryvXmSWpYmmaPfHeN7hvXfCjjnOHZvHE4FkikM1O34TrjGLGjpQ3+TLc7c9+L+gaGQ35eJOE98GDwHFyCzSVqJxqA02VZyxqOGQzkgvRQWXudq84ruRZWSOWWcFiulkd2to7Jg6PtFVTNvG++o6TgCl2fDd2bqPMRlX8aVQe6bnK1VaFXDhYYCWSBOoyGJgSaPa6nkhO4B0J/8IDcXRtC/s40nZQhBWD5V9qA==,iv:hO1QaED3o7vPIJDtuo+8p2OoMtsyU4tzCOcRANWS/ec=,tag:iwUf3Gf+Yfi7I/IJY6LaIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SUFuTkRRb0lhMGFXNk1O
            dE4vY2p2empXM2xJV1RaeXliVXZpc2dxNVFnCmFCODFzTlJGSzNiYk82L3pCTnlE
            QSs4UVhHOGRHT1E5Zmk2MWE0MWFrbFEKLS0tIENQUUNkUGR0T01TNGlXQVF2N004
            bk9MNmROclBpeUZPV1pFL0s1MjVncDAKo0acdD/ExKRYtax+C7D1sqCOB48U0NqH
            9J/u4tTiUs82QTNJPViDziWmIsgFKh5KAS4n5U5/Z2i91nKEpxSH3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T16:29:32Z"
    mac: ENC[AES256_GCM,data:p4lZjXs02snV3j1ySlI9EOOBLARaDjxP3FRwZRHEMlZct7fguhyWXFN/EUuR1W2AMoVnZexQYe0HU6meQ1JPyCpOnKm2u2iYpGVKWCHuo24cVs4GzIe9y+CEFuyGL4O2Fy8tUH8x5umz0X0LGdinyiV+Z5meDjNqcaAQaQpWLK0=,iv:SK5h9ml6bhzTmdYvzf5ecPCdwkd5FdFN2A5QN+FInmo=,tag:9OCbwZ0EBxXcqpx4/tAvTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
