---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      paperless:
        annotations:
          secret.reloader.stakater.com/reload: paperless-secret

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: paperless-secret

        containers:
          app:
            nameOverride: paperless
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7
            env:
              COMPOSE_PROJECT_NAME: paperless
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_PORT: &port 8000
              PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local:6379
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_TIME_ZONE: "Europe/London"
              PAPERLESS_URL: https://paperless.maunder.co
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_CONSUMPTION_DIR: /data/nas/consume
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/nas/export
              PAPERLESS_MEDIA_ROOT: /data/local/media
              USERMAP_UID: "2000"
              USERMAP_GID: "2000"
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
              PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
            probes:
              startup:
                enabled: false

          gotenberg:
            image:
              repository:  gotenberg/gotenberg
              tag: 8
            command:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"

          tika:
            image:
              repository: docker.io/apache/tika
              tag: 3.1.0.0

    service:
      app:
        controller: paperless
        ports:
          http:
            port: *port

      gotenberg:
        controller: paperless
        ports:
          http:
            port: 3000

      tika:
        controller: paperless
        ports:
          http:
            port: 9998

    ingress:
      app:
        className: "internal"
        hosts:
          - host: paperless.maunder.co
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: paperless-data
        advancedMounts:
          paperless:
            app:
              - path: /data/local/

      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Documents
        advancedMounts:
          paperless:
            app:
              - path: /data/nas
