---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snipman-secret
    template:
      engineVersion: v2
      data:
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .DB_USER }}"
        DB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        DB_DATABASE: "snipman"
        INIT_POSTGRES_DBNAME: "snipman"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        APP_KEY: "{{ .APP_KEY}}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: snipman
