---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
log:
  level: 'debug'

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://lldap.security.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=maunder,dc=co
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: cn=readonly,ou=people,dc=maunder,dc=co
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: mnaunder_session
      domain: maunder.co
      authelia_url: https://auth.maunder.co
      default_redirection_url: https://maunder.co
  redis:
    host: dragonfly.database.svc.cluster.local
    database_index: 1

notifier:
  disable_startup_check: true
  smtp:
    address: smtp-relay.network.svc.cluster.local:25
    sender: Authelia <authelia@maunder.co>
    disable_require_tls: true

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules: []

identity_validation:
  reset_password:
    jwt_secret: "{{ .authelia_jwt_secret }}"
