---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      calibre:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: v7.14.0-ls291@sha256:9046cd7b0b1d1de819af5815bb62f1436d5b04c4425b949ca2310f4c32bdcfe4
            env:
              TZ: Europe/London
              PUID: 2000
              PGID: 2000
              CUSTOM_PORT: &port 80
            resources:
              requests:
                cpu: 10m
    service:
      app:
        controller: calibre
        ports:
          http:
            port: *port
          httpweb:
            port: 8081
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.maunder.co"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: calibre
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books
        globalMounts:
          - path: /books
