---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdata
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: netdata-secret
    template:
      engineVersion: v2
      data:
        NETDATA_CLAIM_TOKEN: "{{ .NETDATA_CLAIM_TOKEN }}"
        NETDATA_CLAIM_ROOMS: "{{ .NETDATA_CLAIM_ROOMS }}"
  dataFrom:
    - extract:
        key: netdata
