---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      version: 3.7.102
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    parent:
      envFrom: &envFrom
        - secretRef:
            name: netdata-secret
      claiming:
        enabled: true

    child:
      envFrom: *envFrom
      claiming:
        enabled: true

