---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-microservices
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.136.0
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
            envFrom:
              - secretRef:
                  name: immich-secret
    service:
      app:
        controller: main
        ports:
          http:
            port: 2283
    persistence:
      photos:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Photos
        globalMounts:
          - path: /usr/src/app/upload
      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Pictures
        globalMounts:
          - path: /storage/Pictures
