apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ovWCQLvQJ3fvlZOUGuBS1G6S9PAuzCVsSauWzsJO5ReqhSi4bE9qsw==,iv:4e5RgBCTOLcjWyzBywQFWBNP7WLH7n9Taj/Z0T5Fc7E=,tag:n4QW/CkbSpCtT/Ww9mLFew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQXdXcVRkNXhmdytuRHlT
            TmkvNERQU0d6LzVCaGJ4c0x4N1lnNlpFM1drCnVJQVpEM3grVXNIUDdkVWhkOVg1
            OEtETGhrZUlwV3ZlSGZvbHlEdjVoWjAKLS0tIFdtakVOZzRFRk5Lcno3V3VZVlhZ
            ZXpQdkIvRkI3WDg4dEtNSWJPZ1hBWVUK0dXzu7dTg2puIiD8Xsq0S9RncBcM/bSa
            R1flUEq0R9Dr/M7TwjsDOYmNSzFrA7Bm0qT0+zpED0AUmzqMxG0Plw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T18:53:31Z"
    mac: ENC[AES256_GCM,data:6VzsxUjf59DVhrj4tezpxjnQg6aq3yLSYivF3zk1s9wLEkX0EAshi29kSBxUig88OQoMjX9TkhnrTtGkynNwJa82q7ik9wGSYWzO6mQmD3kevOBmMr2t2XWEvq5LGtB4Mszko2nn7/umsP8fDHE8M+KnvoHkK0YR8RoZizEEj30=,iv:MhBLIFweWBZLvJcuy2a5qpSY1/8056XcK2u1ZWtyT+8=,tag:NqMEFsgAIoSqINpU2+8XfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
