---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolman-config
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
