---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-machine-learning-new
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.142.1
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
            env:
              MACHINE_LEARNING_HOST: 0.0.0.0
              MACHINE_LEARNING_PORT: &port 3003
              MACHINE_LEARNING_CACHE_FOLDER: /cache
              TRANSFORMERS_CACHE: /cache
              UPLOAD_LOCATION: /usr/src/app/upload
            envFrom:
              - secretRef:
                  name: immich-new-secret
    service:
      app:
        controller: main
        ports:
          http:
            port: *port
    persistence:
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /cache
      photos:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/ImmichPhotos
        globalMounts:
          - path: /usr/src/app/upload
      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Pictures
        globalMounts:
          - path: /storage/Pictures
