---
# For Reference: https://github.com/prodrigestivill/docker-postgres-backup-local
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres16-backup
  namespace: database
spec:
  schedule: '0 */2 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          enableServiceLinks: false
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000

          containers:
            - name: postgres16-backup
              image: docker.io/prodrigestivill/postgres-backup-local:18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
              imagePullPolicy: IfNotPresent
              command:
                - '/backup.sh'
              envFrom: &envFrom
              - secretRef:
                  name: postgresbackup-secret
              env:
                - name: POSTGRES_HOST
                  value: postgres16-ro.database.svc.cluster.local
                - name: POSTGRES_DB
                  value: 'postgres'
                - name: POSTGRES_CLUSTER
                  value: 'TRUE'
                - name: POSTGRES_EXTRA_OPTS
                  value: ''
                - name: BACKUP_KEEP_MINS
                  value: '1440'
                - name: TZ
                  value: "Europe/London"

              volumeMounts:
                - name: nas-backups
                  mountPath: /backups

          restartPolicy: OnFailure

          volumes:
            - name: nas-backups
              nfs:
                server: '192.168.1.100'
                path: '/mnt/Data/Backup/postgres'
