---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      hosts:
        - host: &host headlamp.maunder.co
          paths:
            - path: /
              type: Prefix
      tls:
       - hosts:
           - *host
    config:
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: networking.k8s.io
              version: v1
              kind: Ingress
            patch: |-
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: headlamp
              spec:
                ingressClassName: internal
