---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
spec:
  interval: 5m
  releaseName: k10
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io
      chart: k10
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: kasten
        namespace: flux-system
      interval: 5m
  values:
    clusterName: home-k8s
    auth:
      basicAuth:
        enabled: true
        secretName: k10-secret
    ingress:
      create: true
      class: internal
      host: k10.maunder.co
    services:
      securityContext:
        runAsUser: 2000

