---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kasten-nfs-nas-k10
spec:
  storageClassName: kasten-nas-k10
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.1.100"
    path: /mnt/Data/Backup/Kasten
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-k10
  namespace: system-kasten
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kasten-nas-k10
  resources:
    requests:
      storage: 1Mi
