---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app capacitor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      capacitor:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.4.5@sha256:a50533e72341f829add4f0a1d7d8c505422f2663747f026b6858e9351f2e72e6
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
    serviceAccount:
      create: true
      name: *app
    service:
      app:
        controller: *app
        ports:
          http:
            enabled: true
            port: 9000
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.maunder.co"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
