---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      data:
        config.js: |
          function fetchIndexers(baseUrl, apiKey, tag){
            const buffer = require('child_process').execSync(`curl -fsSL "$${baseUrl}/api/v1/tag/detail?apikey=$${apiKey}"`);
            const response = JSON.parse(buffer.toString('utf8'));
            const indexerIds = response.filter(t => t.label === tag)[0]?.indexerIds ?? [];
            const indexers = indexerIds.map(i => `$${baseUrl}/$${i}/api?apikey=$${apiKey}`);
            console.log(`Loaded $${indexers.length} indexers from Prowlarr`);
            return indexers;
          }
          module.exports = {
            action: "inject",
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            linkCategory: "cross-seed",
            linkDirs: ["/media/Downloads/complete/cross-seed"],
            linkType: "hardlink",
            matchMode: "partial",
            radarr: ["http://radarr.downloader.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}"],
            skipRecheck: true,
            sonarr: ["http://sonarr.downloader.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}"],
            torrentClients: ["qbittorrent:http://qbittorrent-app.downloader.svc.cluster.local:8080"],
            torznab: fetchIndexers("http://prowlarr.downloader.svc.cluster.local", "{{.PROWLARR_API_KEY}}", "cross-seed"),
            useClientTorrents: true
          }
  dataFrom:
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: cross-seed
