---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-downloader
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      calibre-web-downloader:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: latest@sha256:29757639bff2263a0de383e6b4855b09457e6c5944f41e934247bbb9bec5c8b7
              pullPolicy: IfNotPresent
            env:
              - name: FLASK_PORT
                value: 8084
              - name: UID
                value: 2000
              - name: GID
                value: 2000
              - name: USE_CF_BYPASS
                value: true
              - name: CLOUDFLARE_PROXY_URL
                value: http://localhost:8000
              - name: INGEST_DIR
                value: /books/Import/cwa-book-ingest
              - name: BOOK_LANGUAGE
                value: en
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
          bypass:
            image:
              repository: ghcr.io/sarperavci/cloudflarebypassforscraping
              tag: latest@sha256:18b70c68b68c21d1cc6c65e8c5eec9ba0e12174f46f1f0952106388ebfe1fe09
              pullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 10m
                memory: 128Mi

    service:
      app:
        controller: calibre-web-downloader
        ports:
          http:
            port: 8084

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        hosts:
          - host: book-downloader.maunder.co
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-web-downloader
        advancedMounts:
          calibre-web-downloader:
            app:
              - path: /config

      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books
        globalMounts:
          - path: /books
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
