---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:

    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V2.1.2

            env:
              CACHE_DIR: /cache
              TZ: "Europe/London"
              PUID: 2000
              PGID: 2000
              DOCKER_MODS: >-
                {{- $items := list
                  "// renovate: lsio-docker-mod"
                  "ghcr.io/linuxserver/mods:universal-calibre-v7.16.0"
                -}}
                {{- $filtered := list -}}
                {{- range $item := $items -}}
                  {{- if not (hasPrefix "//" $item) -}}
                    {{- $filtered = append $filtered $item -}}
                  {{- end -}}
                {{- end -}}
                {{- $filtered | join "|" -}}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        hosts:
          - host: calibre-web.maunder.co
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-web
        advancedMounts:
          calibre-web:
            app:
              - path: /config

      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books
        globalMounts:
          - path: /books

      injest:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books/Import/cwa-book-ingest
        globalMounts:
          - path: /cwa-book-ingest

      lib:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books/Calibre Library
        globalMounts:
          - path: /calibre-library

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
