---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:

    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V3.1.2

            env:
              CACHE_DIR: /cache
              TZ: "Europe/London"
              PUID: 2000
              PGID: 2000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: &port 8083
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  # S6
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - DAC_OVERRIDE
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        hosts:
          - host: calibre-web.maunder.co
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-web
        advancedMounts:
          calibre-web:
            app:
              - path: /config

      newlibary:
        existingClaim: calibre-web-lib
        advancedMounts:
          calibre-web:
            app:
              - path: /calibre-library

      media:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books
        globalMounts:
          - path: /books

      injest:
        type: nfs
        server: 192.168.1.100
        path: /mnt/Data/Media/Books/Import/cwa-book-ingest
        globalMounts:
          - path: /cwa-book-ingest

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
