---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-tracker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-tracker-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: &dbName speedtest_tracker
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser "{{ .SPEEDTEST_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .SPEEDTEST_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        DB_HOST: *dbHost
        DB_PORT: "5432"
        DB_USERNAME: *dbUser
        DB_PASSWORD: *dbPass
        DB_DATABASE: *dbName

        APP_KEY: "{{ .SPEEDTEST_APP_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: speedtest
