---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      speedtesttracker:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: speedtest-tracker-secret
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/speedtest-tracker
              tag: 1.0.2
            env:
              - name: DISPLAY_TIMEZONE
                value: 'Europe/London'
              - name: SPEEDTEST_SCHEDULE
                value: '0 */4 * * *'
              - name: PRUNE_RESULTS_OLDER_THAN
                value: '90'
              - name: PUBLIC_DASHBOARD
                value: 'true'
              - name: DB_CONNECTION
                value: 'pgsql'
            envFrom: *envFrom
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: speedtesttracker
        ports:
          http:
            port: &port 80
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.maunder.co
        className: internal
        hosts:
          - host: speedtest.maunder.co
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: emptyDir
