---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: *name
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
    extraArgs:
      - --pihole-server=http://192.168.1.250
      - --ignore-ingress-tls-spec
      - --ingress-class=internal
    policy: sync
    sources: ["ingress", "service"]
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
