apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:vA8OLCWA+2r4aGVZ9OlJBnVvOCuTjrcZ8b4yEn7vhtedS/oCEyxNfg==,iv:l0Zbsi971gr7SJ8MLNgPqfPLc70Ry91Jm2Wjx+Xs81Q=,tag:7blWLkkRMBW2+Gl04QGgPA==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:epw4ys63rEJNaQ==,iv:z1iddCERRJmmKHIx3ns3GSfKoRzI22Dkh8XCT37S60Y=,tag:mYM8irhsvdi+8FnbuiefCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ24ybnpmbDdrWTlCaXFh
            U0R3TlZZb09lNS9DRFk5NXhmaVkxOGVQbjFJCmU1Q0t4TGhCSHNQNmJYZEM2dVln
            SDI1aUQxMlZiWXZpVHdaYjNwa2RuaFUKLS0tIEFGaWRQREtxT0JGQjdqNERRY2hZ
            SDU4RjlaSHQ1MGtiVFRud3o2a0hTbU0Kj/zAk3TFNu0Bc6r+BoRB/ceC/0mmaExC
            3EXH5PwHqITxVfWfoIqkiwr63CeSBDxZAT72ptr5djxvnZ46xT7v0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T18:41:18Z"
    mac: ENC[AES256_GCM,data:tijoS9CC9u/JsBlMXq0azuDlkFugfalpi9D/687gZODUum03CxTYRvO0+UrTMh1lEAG3zgC3tfc3Mi6iGW8SAkIEAG9TpWH8LNru9C0FxJ6ubB9SUmJOxpfR/yVRLxQUd1IDgUO+lPWYrtTptCw/NdKTTVniOh2pA0OBnt1aUpE=,iv:EiTbECLzDi5Yk+kj23EuIWE8+Ex3FRJt01BPENQP6wo=,tag:+oojtzQltCqeMQ4xnK28SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
