apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9n372yOQJczBj6TVQBaZV59E+6sHqujb0OTxL5/Zdi4emFxQ/5Ibgg==,iv:/8W63Goo0YrUDwlR51SDvUrTcDDWBQIUg3LQIas8lUY=,tag:6j1Em2x65dfSobWzQRbYwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYUthWWFFQklINkdKdEFr
            V3F1OGp2SDJwQ1pMT1NxZ0IwVElQVjBrZFdVCmovRTNwRFdDTHV1SHZxOE5qby9W
            MUFiOVRoUTlyckdRNDl3Rm5ZbmNudlkKLS0tIDR2VWRQaU1kYnA3bEEyM0orTXhh
            WEUvcDVGVGx1WVJiSnZ5R0RYK1Q2d0UKVdbyw+AXM+1E32StdyBDA7dY9TsH6HzB
            vCvDNlzyO9UnvWT0Bh+Rv9qtnlCzh1VQySJfG4lHpdCYhVA1g2oRYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T16:29:32Z"
    mac: ENC[AES256_GCM,data:AVAAsJnXHi95yP9ALhnJLPrxBeTQEqdcioIYB8YQedc4maiWWm+QZCMe/67FXlTvKKMqSRvFjo5R2IQazohaQcUECsnL1nOPxf3lbZ2f668XvKLWPUmKi9zELt4vFjiuyMuMJZbXPo7h4AFhkm2948wsI2tJVOOtQ2Lc5gvsUjM=,iv:K1sEbQUtHmkTEWkPyMC1hBaPc8PE1GaXgYhLKGT9ZRQ=,tag:bw0xk6rn6ncy2JozMap0Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
