apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:vA8OLCWA+2r4aGVZ9OlJBnVvOCuTjrcZ8b4yEn7vhtedS/oCEyxNfg==,iv:l0Zbsi971gr7SJ8MLNgPqfPLc70Ry91Jm2Wjx+Xs81Q=,tag:7blWLkkRMBW2+Gl04QGgPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ24ybnpmbDdrWTlCaXFh
            U0R3TlZZb09lNS9DRFk5NXhmaVkxOGVQbjFJCmU1Q0t4TGhCSHNQNmJYZEM2dVln
            SDI1aUQxMlZiWXZpVHdaYjNwa2RuaFUKLS0tIEFGaWRQREtxT0JGQjdqNERRY2hZ
            SDU4RjlaSHQ1MGtiVFRud3o2a0hTbU0Kj/zAk3TFNu0Bc6r+BoRB/ceC/0mmaExC
            3EXH5PwHqITxVfWfoIqkiwr63CeSBDxZAT72ptr5djxvnZ46xT7v0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T18:53:31Z"
    mac: ENC[AES256_GCM,data:87D3+mOJNzq2ogfcCNgIuFLG44ZKN1CLKZgifd5v2EpJOJDAIGNI97rw8CS8K5ueIe8QL195XebpKkBoJGhHcyzgjVd/bIpYI2BKEgx9pKI7MJal30DXtAarL+5d7udU66BOL3MYyqySfTJ3yqxPAKGXQh8X33F8plJ4HY8MlRo=,iv:pPf/WdOJ8gxyuAmNevoYN3oDNKcF/EGNMMtJAeNCiNQ=,tag:010htD8nvQ6VqmfOjVsKuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
