apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DjBACKH0hsYQiDafyWAaDGkV5bDPfYRMlek+6T5dxH+5fV39fWc+/w==,iv:94r/PZrv8pdZqN5SLKjVxyW5fLDtazzSP4Kpp0JEhWg=,tag:t2fkM3+74LnSKzTif8kZIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199u8xqqny7znxenfx7qf8uvl6garnkggd9g75kq0eeat89rzygqqy62c8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdWZieDI5WW5HNnhudkZk
            YS9IRmRpVndDbFZZbTdxeGdiMkJ2NDZSb1NvCmoveWhOUUJTbW9ROUdJeEJpNHNt
            MVNpN1hWeSt4cDdRT3krbDRWY2dUZGsKLS0tIFJYSFFXd0h6R0tOQ2I1MGxuM2hJ
            WjdnNXdXUjVpV3ZvenpvS0E3czRja0EKuG/XnIx042mYb2ocwlsH0yCjjCCU/idb
            g7wpg3L3BngHAKclm39hFulKQvI5KCRg530m9T4qYFjz78zP02VK+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T20:31:41Z"
    mac: ENC[AES256_GCM,data:GrqXZhv+Hho2boo5TTdcoUhnqsqDeyoUNY4QLWkEsRdJgJsrzw5MNtY7q8Cz6YIztyuJoMHHbcn7Ydn1ZxktAkNtywUaYPufmwTz8ey9pVPi4tzuUOVJS8Bytk+zJ+aZhvdUUoUAW48oFDMk3ElILDM29Ns7VVh6/lTtnEDgTfc=,iv:pWtrY9BuJGgz5zBtYOpFCiovMgo0DFMDrryONB+4l8s=,tag:4eGI9m5Cz0UCK+GbJsE4WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
