---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  driftDetection:
    mode: enabled

  values:
    defaultPodOptions:
      priorityClassName: system-node-critical

    controllers:
      generic-device-plugin:
        type: daemonset
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: 6475ff5d0927c0f25b3a39a661aa657ca190d0ef@sha256:d7d0951df7f11479185fd9fba1c1cb4d9c8f3232d38a5468d6fe80074f2b45d5
            args:
              - --log-level=info
              - --config=/config/config.yaml
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              # privileged: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    persistence:
      config:
        type: configMap
        name: generic-device-plugin-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - readOnly: true
      sys:
        type: hostPath
        hostPath: /sys
        globalMounts:
          - readOnly: true
      var-lib-kubelet-device-plugins:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
