---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_DATABASE_URL: "{{ .LLDAP_DATABASE_URL. }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT__POSTGRES__PORT: "5432"
        INIT_POSTGRES_USER: "{{ .LLDAP_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LLDAP_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: lldap
