---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: postgres16-rw.database.svc.cluster.local:5432
        DB_USERNAME: &dbUser "{{ .IMMICH_POSTGRES_USER }}"
        IMMICH_SERVER_URL: &dbPass "{{ .IMMICH_POSTGRES_PASS }}"
        IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
        IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
        PUBLIC_IMMICH_SERVER_URL: https://photos.maunder.co
        REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
        REDIS_PORT: "6379"
        TZ: "Europe/London"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
