---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-secret
    template:
      engineVersion: v2
      data:
        PIHOLE_PASSWORD: "{{ .PIHOLE_ADMIN_PASSWORD }}"
        PRIMARY_HOST_PASSWORD: "{{ .PIHOLE_ADMIN_PASSWORD }}"
        SECONDARY_HOST_1_PASSWORD: "{{ .PIHOLE_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: pihole
